# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    name: build

    steps:
    
    - name: Set the value
      - run: |
        echo "{OSS_KEY=${{secrets.OSS_KEY}}}" >> $GITHUB_ENV
        echo "OSSOSS_SECRET_KEY=${{secrets.OSS_SECRET}}" >> $GITHUB_ENV

    - name: build-action
      - uses: actions/checkout@v2
      - run: docker-compose up --build -d
        
