# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-lates
    
    steps:
    - name: ssh
      uses: actions/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        user: root
        pass: ${{ secrets.SERVER_PASSWORD }}
        first_ssh: |
          cd ~/project/play-ci
          git pull
          docker compose up --build -d
        
