# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    name: build
      
    steps:
    - uses: actions/checkout@v2
      with:
        OSS_KEY: ${{ secrets.OSS_KEY }}
        OSS_SECRET: ${{ secrets.OSS_SECRET }}
    - run: |
      export OSS_KEY=$OSS_KEY
      export OSS_SECRET=$OSS_SECRET
      docker-compose up --build -d
        
